### ISSUE TITLE
Milestone 2 Issues

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/Song_Key_Mode_and_Popularity_on_Spotify#54]
- [x] Meed a caption for Fig 3.
- [x] Include a conclusion statement. 
- [x] Misspelled _likable_ and _curiosity_ in the report

**Comment by Pall-v** [comment]
- https://github.com/UBC-MDS/Song_Key_Mode_and_Popularity_on_Spotify/issues/36
- https://github.com/UBC-MDS/Song_Key_Mode_and_Popularity_on_Spotify/issues/37

**Comment by sedv8808** [comment]
Added conclusion, added caption for Fig03, corrected spelling mistakes.

**Comment by aimirza** [comment]
I added a couple more issues above
